# Generated by Django 3.1.14 on 2023-07-21 05:03

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
            ],
        ),
    ]
